source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

target 'ChatExample' do
  use_frameworks!
  pod 'MessageKit', :path => '../'
  pod 'InputBarAccessoryView', '~> 5.5.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'CorePlot', :git => 'ssh://git@github.com/Health2Sync/core-plot.git', :branch => 'main'

target 'ChatExampleTests' do
  inherit! :search_paths
end

target 'ChatExampleUITests' do
  inherit! :search_paths
end

end
