source 'https://cdn.cocoapods.org/'

platform :ios, '12.0'

target 'ChatExample' do
  use_frameworks!
  pod 'MessageKit', :path => '../'
  pod 'InputBarAccessoryView', '~> 5.5.0'
  pod 'Kingfisher', '~> 7.0'

target 'ChatExampleTests' do
  inherit! :search_paths
end

target 'ChatExampleUITests' do
  inherit! :search_paths
end

end
